name: gem_image_compare
description: "An internal testing tool for comparing images"
version: 1.0.2

environment:
  sdk: '>=3.4.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  devtools_extensions: ^0.1.1
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  image: ^4.1.7
  flutter_test:
    sdk: flutter
  matcher:
  clipboard: ^0.1.3
  file_saver: ^0.2.12

dev_dependencies:
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true